language: cpp

compiler:
  - gcc

before_install:
   - sudo apt-get install -y nodejs libqt5webkit5-dev
#  - pip install --user cpp-coveralls

script: 
  - mkdir -p build 
  - cd build 
  - ../configure --enable-debug --enable-gcc-coverage
  - make 
  - make test

#after_success:
#  - if [ "$CXX" == "g++" ]; then coveralls -r ../ -e src/tests --gcov-options '\-lp'; fi
